"""Turn reviewed extraction output into dependency-free browser modules."""

from __future__ import annotations

import base64
import json
import re
from pathlib import Path

from PIL import Image


ROOT = Path(__file__).resolve().parents[1]
BUILD = ROOT / "tmp" / "extrusion-build"
SERIES = ["2000", "8000", "8100", "8200", "8300", "8400",
          "8500", "8600", "8700", "8800", "8900", "8950"]


def has_profile(card_path: Path) -> bool:
    with Image.open(card_path) as opened:
        image = opened.convert("L")
    crop = image.crop((12, 12, image.width - 12, round(image.height * 0.65)))
    histogram = crop.histogram()
    return sum(histogram[:235]) / max(1, crop.width * crop.height) > 0.0005


records = []
images = {}
for series in SERIES:
    source = json.loads((BUILD / f"records-{series}.json").read_text(encoding="utf-8"))
    for record in source:
        image_path = BUILD / "images" / record["image"]
        if not image_path.exists() or not has_profile(image_path):
            continue
        key = re.sub(r"[^A-Za-z0-9]+", "-",
                     f"{series}-{record['page']}-{record['cell']}-{record['id']}").strip("-").lower()
        records.append({
            "key": key,
            "id": record["id"],
            "series": record["series"],
            "description": record.get("description", ""),
            "supplier": record.get("supplier", ""),
            "proposed": record.get("proposed", ""),
            "finalDie": record.get("finalDie", ""),
            "status": record.get("status", "Active"),
            "page": record["page"],
            "cell": record["cell"],
        })
        images[key] = base64.b64encode(image_path.read_bytes()).decode("ascii")

records.sort(key=lambda item: (SERIES.index(item["series"]), item["id"], item["page"], item["cell"]))

(ROOT / "js" / "extrusion-records.js").write_text(
    "/* Generated by tools/build-extrusion-data.py from the reviewed engineering masters. */\n"
    f"export const EXTRUSIONS = {json.dumps(records, ensure_ascii=False, separators=(',', ':'))};\n",
    encoding="utf-8",
)
(ROOT / "js" / "extrusion-images.js").write_text(
    "/* Generated profile cards; kept separate so search logic stays reviewable. */\n"
    "export const EXTRUSION_IMAGE_PREFIX = 'data:image/webp;base64,';\n"
    f"export const EXTRUSION_IMAGES = {json.dumps(images, separators=(',', ':'))};\n",
    encoding="utf-8",
)

print(f"{len(records)} extrusion drawings across {len(SERIES)} masters")
print(f"{sum(len(value) for value in images.values()) / 1024 / 1024:.1f} MiB base64 image payload")
